language: go

go:
  - 1.14

services:
  - docker

install:
  - docker pull thezviad/tt-tt || true
  - docker tag thezviad/tt-tt tt-tt || true
  - go install github.com/zviadm/tt/tt

script:
  - tt -tt.rebuild -v ./...

after_success:
  - docker tag tt-tt thezviad/tt-tt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thezviad/tt-tt
